# Generated by Django 5.1.1 on 2024-10-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='section',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
