# Generated by Django 5.1.1 on 2024-10-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_file_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='section',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
