# Generated by Django 5.1.1 on 2024-10-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_file_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
