# Generated by Django 5.1.1 on 2024-09-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user_tag',
        ),
    ]
