# Generated by Django 4.2.8 on 2024-10-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='userprofile/default.jpg', upload_to='userprofile/'),
        ),
    ]
