# Generated by Django 5.1.1 on 2024-09-25 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(editable=False, max_length=4, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('group_image', models.ImageField(blank=True, default='group_images/default.jpg', null=True, upload_to='group_images/')),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
