# Generated by Django 5.1.1 on 2024-09-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_id',
            new_name='group_tag',
        ),
    ]
