# Generated by Django 4.2.8 on 2024-09-26 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_rename_group_id_group_group_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
