// groupConstants.js

export const GROUP_CREATE_REQUEST = 'GROUP_CREATE_REQUEST';
export const GROUP_CREATE_SUCCESS = 'GROUP_CREATE_SUCCESS';
export const GROUP_CREATE_FAIL = 'GROUP_CREATE_FAIL';

export const GROUP_IMAGE_UPLOAD_REQUEST = 'GROUP_IMAGE_UPLOAD_REQUEST';
export const GROUP_IMAGE_UPLOAD_SUCCESS = 'GROUP_IMAGE_UPLOAD_SUCCESS';
export const GROUP_IMAGE_UPLOAD_FAIL = 'GROUP_IMAGE_UPLOAD_FAIL';

export const GROUP_IMAGE_REMOVE_REQUEST = 'GROUP_IMAGE_REMOVE_REQUEST';
export const GROUP_IMAGE_REMOVE_SUCCESS = 'GROUP_IMAGE_REMOVE_SUCCESS';
export const GROUP_IMAGE_REMOVE_FAIL = 'GROUP_IMAGE_REMOVE_FAIL';

export const GROUP_JOIN_REQUEST = 'GROUP_JOIN_REQUEST';
export const GROUP_JOIN_SUCCESS = 'GROUP_JOIN_SUCCESS';
export const GROUP_JOIN_FAIL = 'GROUP_JOIN_FAIL';

export const GROUP_FAVORITE_ADD_REQUEST = 'GROUP_FAVORITE_ADD_REQUEST';
export const GROUP_FAVORITE_ADD_SUCCESS = 'GROUP_FAVORITE_ADD_SUCCESS';
export const GROUP_FAVORITE_ADD_FAIL = 'GROUP_FAVORITE_ADD_FAIL';

export const GROUP_FAVORITE_REMOVE_REQUEST = 'GROUP_FAVORITE_REMOVE_REQUEST';
export const GROUP_FAVORITE_REMOVE_SUCCESS = 'GROUP_FAVORITE_REMOVE_SUCCESS';
export const GROUP_FAVORITE_REMOVE_FAIL = 'GROUP_FAVORITE_REMOVE_FAIL';

export const USER_GROUPS_REQUEST = 'USER_GROUPS_REQUEST';
export const USER_GROUPS_SUCCESS = 'USER_GROUPS_SUCCESS';
export const USER_GROUPS_FAIL = 'USER_GROUPS_FAIL';

export const GROUPS_LIST_REQUEST = 'GROUPS_LIST_REQUEST';
export const GROUPS_LIST_SUCCESS = 'GROUPS_LIST_SUCCESS';
export const GROUPS_LIST_FAIL = 'GROUPS_LIST_FAIL';

export const GROUP_LEAVE_REQUEST = 'GROUP_LEAVE_REQUEST';
export const GROUP_LEAVE_SUCCESS = 'GROUP_LEAVE_SUCCESS';
export const GROUP_LEAVE_FAIL = 'GROUP_LEAVE_FAIL';

export const GROUP_DETAILS_REQUEST = 'GROUP_DETAILS_REQUEST';
export const GROUP_DETAILS_SUCCESS = 'GROUP_DETAILS_SUCCESS';
export const GROUP_DETAILS_FAIL = 'GROUP_DETAILS_FAIL';

export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL';