// groupConstants.js

export const GROUP_CREATE_REQUEST = 'GROUP_CREATE_REQUEST';
export const GROUP_CREATE_SUCCESS = 'GROUP_CREATE_SUCCESS';
export const GROUP_CREATE_FAIL = 'GROUP_CREATE_FAIL';

export const GROUP_IMAGE_UPLOAD_REQUEST = 'GROUP_IMAGE_UPLOAD_REQUEST';
export const GROUP_IMAGE_UPLOAD_SUCCESS = 'GROUP_IMAGE_UPLOAD_SUCCESS';
export const GROUP_IMAGE_UPLOAD_FAIL = 'GROUP_IMAGE_UPLOAD_FAIL';