export const TITLE_LIST_REQUEST = 'TITLE_LIST_REQUEST'
export const TITLE_LIST_SUCCESS = 'TITLE_LIST_SUCCESS'
export const TITLE_LIST_FAIL = 'TITLE_LIST_FAIL'

export const TITLE_CREATE_REQUEST = 'TITLE_CREATE_REQUEST'
export const TITLE_CREATE_SUCCESS = 'TITLE_CREATE_SUCCESS'
export const TITLE_CREATE_FAIL = 'TITLE_CREATE_FAIL'

export const TITLE_UPDATE_REQUEST = 'TITLE_UPDATE_REQUEST'
export const TITLE_UPDATE_SUCCESS = 'TITLE_UPDATE_SUCCESS'
export const TITLE_UPDATE_FAIL = 'TITLE_UPDATE_FAIL'

export const TITLE_DELETE_REQUEST = 'TITLE_DELETE_REQUEST'
export const TITLE_DELETE_SUCCESS = 'TITLE_DELETE_SUCCESS'
export const TITLE_DELETE_FAIL = 'TITLE_DELETE_FAIL'

export const VIDEO_LIST_REQUEST = 'VIDEO_LIST_REQUEST'
export const VIDEO_LIST_SUCCESS = 'VIDEO_LIST_SUCCESS'
export const VIDEO_LIST_FAIL = 'VIDEO_LIST_FAIL'

export const VIDEO_CREATE_REQUEST = 'VIDEO_CREATE_REQUEST'
export const VIDEO_CREATE_SUCCESS = 'VIDEO_CREATE_SUCCESS'
export const VIDEO_CREATE_FAIL = 'VIDEO_CREATE_FAIL'

export const VIDEO_UPDATE_REQUEST = 'VIDEO_UPDATE_REQUEST'
export const VIDEO_UPDATE_SUCCESS = 'VIDEO_UPDATE_SUCCESS'
export const VIDEO_UPDATE_FAIL = 'VIDEO_UPDATE_FAIL'

export const VIDEO_DELETE_REQUEST = 'VIDEO_DELETE_REQUEST'
export const VIDEO_DELETE_SUCCESS = 'VIDEO_DELETE_SUCCESS'
export const VIDEO_DELETE_FAIL = 'VIDEO_DELETE_FAIL'

export const FILE_LIST_REQUEST = 'FILE_LIST_REQUEST'
export const FILE_LIST_SUCCESS = 'FILE_LIST_SUCCESS'
export const FILE_LIST_FAIL = 'FILE_LIST_FAIL'

export const FILE_CREATE_REQUEST = 'FILE_CREATE_REQUEST'
export const FILE_CREATE_SUCCESS = 'FILE_CREATE_SUCCESS'
export const FILE_CREATE_FAIL = 'FILE_CREATE_FAIL'

export const FILE_UPDATE_REQUEST = 'FILE_UPDATE_REQUEST'
export const FILE_UPDATE_SUCCESS = 'FILE_UPDATE_SUCCESS'
export const FILE_UPDATE_FAIL = 'FILE_UPDATE_FAIL'

export const FILE_DELETE_REQUEST = 'FILE_DELETE_REQUEST'
export const FILE_DELETE_SUCCESS = 'FILE_DELETE_SUCCESS'
export const FILE_DELETE_FAIL = 'FILE_DELETE_FAIL'


export const GET_FILES_AND_VIDEOS_REQUEST = 'GET_FILES_AND_VIDEOS_REQUEST';
export const GET_FILES_AND_VIDEOS_SUCCESS = 'GET_FILES_AND_VIDEOS_SUCCESS';
export const GET_FILES_AND_VIDEOS_FAIL = 'GET_FILES_AND_VIDEOS_FAIL';