export const TODOLIST_LIST_REQUEST = 'TODOLIST_LIST_REQUEST';
export const TODOLIST_LIST_SUCCESS = 'TODOLIST_LIST_SUCCESS';
export const TODOLIST_LIST_FAIL = 'TODOLIST_LIST_FAIL';

export const TODOLIST_CREATE_REQUEST = 'TODOLIST_CREATE_REQUEST';
export const TODOLIST_CREATE_SUCCESS = 'TODOLIST_CREATE_SUCCESS';
export const TODOLIST_CREATE_FAIL = 'TODOLIST_CREATE_FAIL';

export const TODOLIST_UPDATE_REQUEST = 'TODOLIST_UPDATE_REQUEST';
export const TODOLIST_UPDATE_SUCCESS = 'TODOLIST_UPDATE_SUCCESS';
export const TODOLIST_UPDATE_FAIL = 'TODOLIST_UPDATE_FAIL';

export const TODOLIST_DELETE_REQUEST = 'TODOLIST_DELETE_REQUEST';
export const TODOLIST_DELETE_SUCCESS = 'TODOLIST_DELETE_SUCCESS';
export const TODOLIST_DELETE_FAIL = 'TODOLIST_DELETE_FAIL';